scss_files: "scss/**/*.scss"
linters:
  BorderZero:
    enabled: false
  IdSelector:
    enabled: false
  ImportantRule:
    enabled: false
  LeadingZero:
    enabled: true
    style: include_zero
  NestingDepth:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: false
  SelectorFormat:
    enabled: false
  StringQuotes:
    enabled: true
    style: double_quotes
  VendorPrefix:
    enabled: false
